syntax on
set number
set ruler
set showcmd
set incsearch
set nowrap 

set tabstop=4
set softtabstop=0
set shiftwidth=4
set expandtab
set smarttab

" COC settings
set hidden
set nobackup
set nowritebackup
set cmdheight=2

" Color scheme settings
colorscheme gruvbox
:set bg=dark
 
" Key remaps
nnoremap o o <esc>
nnoremap O O <esc>

let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='gruvbox'

call plug#begin('~/.vim/plugged')
    
    Plug 'morhetz/gruvbox'
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    
call plug#end()
